apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mxcore
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  baseUrl: {{ .Values.mxcore.baseUrl }}
  allowedOrigins: {{ .Values.mxcore.allowedOrigins | toJson }}
