{{ if .Values.mxcore.encryption.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-encryption-secret
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  key: {{ .Values.mxcore.encryption.key | b64enc }}
{{- end }}
